---
title: Little Lilly Website
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: magic@littlelilly.no
description: |
  Automagically send your favorite Instagram photos as a letter to your friends and family.
baseurl: ''
url: http://littlelilly.no
twitter_username: lilly_labs
github_username: lillylabs
markdown: kramdown
