---
title: Little Lilly
timezone: UTC
collections:
  page-sections:
    title: Page Sections
    output: false
  pages:
    title: Pages
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
