<<<<<<< HEAD
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Little Lilly
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: magic$littlelilly.no
description: > # this means to ignore newlines until "baseurl:"
  Automagically send your favorite Instagram photos as a letter to your friends and family.
baseurl: ''
url: http://littlelilly.no
twitter_username: lilly_labs
github_username: lillylabs
markdown: kramdown
